### ISSUE TITLE
I need documentation

### ISSUE THREAD

**Issue by Paca** [prabhjots/crm-dynamics-angular-service#1]
Hello, 

Can you provide a simple example usage of this Module ? With dependence injection ?
In particular the retrieves method of Rest svc.

Thank you for your work.

Regards,

**Comment by prabhjots** [comment]
Hi @Paca. I have updated the readme file. Hope that would help. Let me know if you need further clarification.

**Comment by Paca** [comment]
Hi @prabhjots, It's perfect all work fine, and injection dependence is much more clear for me. You can close the issue if you want.
Have a nice day.

PS: sorry for the delay, lot of work! ;)
